export const memberData = [
	{
		id: '1',
		name: 'ROHAN SMITHWICK',
		email: 's-rsmithwick@lwsd.org',
		startTime: '9/29/23 15:48:57',
		lastModifiedTime: '10/26/23 15:36:18',
		completionTime: '9/29/23 15:49:48',
		events: [
			'Data Science and Analytics*',
			'Dragster Design*',
			'Photographic Technology',
			'Architectural Design*',
		],
		backups: ['Board Game Design*', 'Video Game Design*'],
	},
	{
		id: '2',
		name: 'CALEB SKENANDORE',
		email: 's-cskenandore@lwsd.org',
		startTime: '9/29/23 15:49:27',
		lastModifiedTime: '',
		completionTime: '9/29/23 15:50:18',
		events: [
			'Computer-Aided Design (CAD), Engineering',
			'Dragster Design*',
			'Engineering Design*',
			'Video Game Design*',
		],
		backups: [
			'Computer-Aided Design (CAD), Architecture',
			'Structural Design and Engineering*',
		],
	},
	{
		id: '3',
		name: 'VARUN PATANKAR',
		email: 's-vpatankar@lwsd.org',
		startTime: '9/29/23 15:49:40',
		lastModifiedTime: '',
		completionTime: '9/29/23 15:50:41',
		events: [
			'Software Development*',
			'Technology Problem Solving',
			'Coding',
			'Video Game Design*',
		],
		backups: ['Technology Bowl', 'Webmaster*'],
	},
	{
		id: '5',
		name: 'FIONA BRENNAN',
		email: 's-fbrennan@lwsd.org',
		startTime: '9/29/23 15:49:50',
		lastModifiedTime: '',
		completionTime: '9/29/23 15:51:23',
		events: [
			'Biotechnology Design*',
			'Extemporaneous Speech',
			'Forensic Science',
			'Photographic Technology',
		],
		backups: ['Essays on Technology', 'On Demand Video'],
	},
	{
		id: '6',
		name: 'AKSHAT KHATNANI',
		email: 's-akhatnani@lwsd.org',
		startTime: '9/29/23 15:50:30',
		lastModifiedTime: '',
		completionTime: '9/29/23 15:51:40',
		events: [
			'Audio Podcasting*',
			'Computer-Aided Design (CAD), Architecture',
			'Debating Technological Issues*',
			'Extemporaneous Speech',
		],
		backups: ['Essays on Technology', 'Silent Film (Washington Only)'],
	},
	{
		id: '7',
		name: 'TESS MAGEE',
		email: 's-tmagee@lwsd.org',
		startTime: '9/29/23 15:49:57',
		lastModifiedTime: '10/12/23 16:11:28',
		completionTime: '9/29/23 15:51:46',
		events: [
			'Audio Podcasting*',
			"Children's Stories*",
			'Architectural Design*',
			'Photographic Technology',
		],
		backups: ['Technology Problem Solving', 'Fashion Design and Technology*'],
	},
	{
		id: '8',
		name: 'ADAM ABDEL-RAHMANSAMIR',
		email: 's-aabdelrahmansamir@lwsd.org',
		startTime: '9/29/23 15:49:02',
		lastModifiedTime: '',
		completionTime: '9/29/23 15:51:46',
		events: [
			'On Demand Video',
			'Computer-Aided Design (CAD), Engineering',
			'Extemporaneous Speech',
			'Essays on Technology',
		],
		backups: [
			'Computer-Aided Design (CAD), Architecture',
			'Video Game Design*',
		],
	},
	{
		id: '9',
		name: 'SAMUEL ATKINSON',
		email: 's-satkinson@lwsd.org',
		startTime: '9/29/23 15:49:16',
		lastModifiedTime: '10/26/23 15:33:54',
		completionTime: '9/29/23 15:51:51',
		events: [
			'Photographic Technology',
			'VEX Robotics*',
			'Video Game Design*',
			'Architectural Design*',
		],
		backups: ['Virtual Reality Visualization (VR)*', 'Engineering Design*'],
	},
	{
		id: '10',
		name: 'MITHRAN VIJAYANAND',
		email: 's-mvijayanand@lwsd.org',
		startTime: '9/29/23 15:50:08',
		lastModifiedTime: '',
		completionTime: '9/29/23 15:52:00',
		events: [
			'Biotechnology Design*',
			'Drone Challenge (UAV)*',
			'Forensic Science',
			'Debating Technological Issues*',
		],
		backups: ['Trebuchet (Washington Only)', 'Flight Endurance*'],
	},
	{
		id: '11',
		name: 'VARSHINI CHANDRASEKHAR',
		email: 's-VCHANDRASEKHAR@lwsd.org',
		startTime: '9/29/23 15:49:08',
		lastModifiedTime: '10/3/23 17:12:30',
		completionTime: '9/29/23 15:52:22',
		events: [
			'Audio Podcasting*',
			'Debating Technological Issues*',
			'Essays on Technology',
			'Extemporaneous Speech',
			'Career Prep* (Washington Only)',
			'Music Production*',
		],
		backups: ["Children's Stories*", 'Data Science and Analytics*'],
	},
	{
		id: '12',
		name: 'ANNA MELOMED',
		email: 's-amelomed@lwsd.org',
		startTime: '9/29/23 15:51:07',
		lastModifiedTime: '10/5/23 17:33:31',
		completionTime: '9/29/23 15:52:44',
		events: [
			'Data Science and Analytics*',
			'Software Development*',
			'Virtual Reality Visualization (VR)*',
			'Webmaster*',
			'On Demand Video',
			'Silent Film (Washington Only)',
		],
		backups: ['Debating Technological Issues*', 'On Demand Video'],
	},
	{
		id: '14',
		name: 'ARUN CHANDAR',
		email: 's-achandar@lwsd.org',
		startTime: '9/29/23 15:51:31',
		lastModifiedTime: '10/12/23 15:06:14',
		completionTime: '9/29/23 15:53:46',
		events: [
			'Engineering Design*',
			'On Demand Video',
			'VEX Robotics*',
			'Webmaster*',
			"Children's Stories*",
			'Architectural Design*',
		],
		backups: [
			'Virtual Reality Visualization (VR)*',
			'Debating Technological Issues*',
		],
	},
	{
		id: '15',
		name: 'BETHANY HU',
		email: 's-behu@lwsd.org',
		startTime: '9/29/23 15:51:24',
		lastModifiedTime: '',
		completionTime: '9/29/23 15:54:02',
		events: [
			'Computer-Aided Design (CAD), Engineering',
			'STEM Mass Media (Washington Only)',
			'Transportation Modeling*',
			'Technology Problem Solving',
		],
		backups: ['Board Game Design*', 'Career Prep* (Washington Only)'],
	},
	{
		id: '17',
		name: 'BARUN ACHARYA',
		email: 's-bacharya@lwsd.org',
		startTime: '9/29/23 15:55:02',
		lastModifiedTime: '',
		completionTime: '9/29/23 15:56:45',
		events: [
			'Flight Endurance*',
			'On Demand Video',
			'Technology Bowl',
			'Board Game Design*',
		],
		backups: ['Drone Challenge (UAV)*', 'Forensic Science'],
	},
	{
		id: '18',
		name: 'AADARSH RAO',
		email: 's-arao@lwsd.org',
		startTime: '9/29/23 15:57:17',
		lastModifiedTime: '',
		completionTime: '9/29/23 16:01:01',
		events: [
			'Biotechnology Design*',
			'Drone Challenge (UAV)*',
			'Forensic Science',
			'Debating Technological Issues*',
		],
		backups: ['Flight Endurance*', 'Trebuchet (Washington Only)'],
	},
	{
		id: '19',
		name: 'TAIGA SAKAKIHARA',
		email: 's-tasakakihara@lwsd.org',
		startTime: '9/29/23 15:49:17',
		lastModifiedTime: '',
		completionTime: '9/29/23 16:03:51',
		events: [
			'Computer-Aided Design (CAD), Engineering',
			'Engineering Design*',
			'Flight Endurance*',
			'VEX Robotics*',
		],
		backups: ['Technology Bowl', 'Transportation Modeling*'],
	},
	{
		id: '20',
		name: 'TYLER HAIL',
		email: 's-thail@lwsd.org',
		startTime: '9/29/23 16:15:51',
		lastModifiedTime: '',
		completionTime: '9/29/23 16:17:03',
		events: [
			'Board Game Design*',
			'Dragster Design*',
			'Structural Design and Engineering*',
			'Trebuchet (Washington Only)',
		],
		backups: ['Transportation Modeling*', 'Technology Problem Solving'],
	},
	{
		id: '21',
		name: 'VIJAY PATANKAR',
		email: 's-vipatankar@lwsd.org',
		startTime: '9/29/23 17:55:23',
		lastModifiedTime: '10/12/23 10:37:06',
		completionTime: '9/29/23 17:57:20',
		events: [
			'Debating Technological Issues*',
			'Coding',
			'Career Prep* (Washington Only)',
			'Data Science and Analytics*',
		],
		backups: ['Data Science and Analytics*', 'Coding'],
	},
	{
		id: '22',
		name: 'VEER SHAH',
		email: 's-veshah@lwsd.org',
		startTime: '9/29/23 18:12:42',
		lastModifiedTime: '',
		completionTime: '9/29/23 18:13:48',
		events: [
			'Biotechnology Design*',
			'On Demand Video',
			'Video Game Design*',
			'Forensic Science',
		],
		backups: ['Drone Challenge (UAV)*', 'Silent Film (Washington Only)'],
	},
	{
		id: '23',
		name: 'HANA JACOBS',
		email: 's-hjacobs@lwsd.org',
		startTime: '9/29/23 19:03:26',
		lastModifiedTime: '10/9/23 13:53:44',
		completionTime: '9/29/23 19:03:40',
		events: [
			'Architectural Design*',
			'VEX Robotics*',
			'Dragster Design*',
			'Drone Challenge (UAV)*',
			'Computer-Aided Design (CAD), Architecture',
		],
		backups: [
			'Engineering Design*',
			'Computer-Aided Design (CAD), Engineering',
		],
	},
	{
		id: '24',
		name: 'TYLER SCHWEIZER',
		email: 's-TSCHWEIZER@lwsd.org',
		startTime: '9/29/23 19:51:27',
		lastModifiedTime: '',
		completionTime: '9/29/23 20:21:32',
		events: [
			'Drone Challenge (UAV)*',
			'Senior Solar Sprint*',
			'Trebuchet (Washington Only)',
			'Video Game Design*',
		],
		backups: ['Software Development*', 'Coding'],
	},
	{
		id: '25',
		name: 'ALEXANDER BYKOV',
		email: 's-abykov@lwsd.org',
		startTime: '9/29/23 22:18:30',
		lastModifiedTime: '',
		completionTime: '9/29/23 22:22:09',
		events: [
			'Drone Challenge (UAV)*',
			'VEX Robotics*',
			'On Demand Video',
			'Dragster Design*',
		],
		backups: ['Flight Endurance*', 'Trebuchet (Washington Only)'],
	},
	{
		id: '26',
		name: 'BHAVYA KOTTAPALLI',
		email: 's-bkottapalli@lwsd.org',
		startTime: '9/30/23 6:07:45',
		lastModifiedTime: '',
		completionTime: '9/30/23 6:08:31',
		events: [
			'Biotechnology Design*',
			'Fashion Design and Technology*',
			'Forensic Science',
			'Music Production*',
		],
		backups: ['Architectural Design*', 'Debating Technological Issues*'],
	},
	{
		id: '27',
		name: 'SHIVANI VENKATESH',
		email: 's-svenkatesh@lwsd.org',
		startTime: '9/29/23 17:05:19',
		lastModifiedTime: '10/26/23 15:47:15',
		completionTime: '9/30/23 13:49:55',
		events: [
			'Biotechnology Design*',
			'Forensic Science',
			'Fashion Design and Technology*',
			'Music Production*',
		],
		backups: ['Debating Technological Issues*', 'VEX Robotics*'],
	},
	{
		id: '28',
		name: 'FATIMA GALACGAC',
		email: 's-fagalacgac@lwsd.org',
		startTime: '9/30/23 13:53:34',
		lastModifiedTime: '',
		completionTime: '9/30/23 13:55:50',
		events: [
			'Biotechnology Design*',
			"Children's Stories*",
			'Forensic Science',
			'Fashion Design and Technology*',
			'Engineering Design*',
		],
		backups: ['Board Game Design*', 'Video Game Design*'],
	},
	{
		id: '29',
		name: 'SENUKA LIYANAGE',
		email: 's-sliyanage@lwsd.org',
		startTime: '9/30/23 21:44:05',
		lastModifiedTime: '',
		completionTime: '9/30/23 21:46:00',
		events: [
			'Software Development*',
			'Virtual Reality Visualization (VR)*',
			'Webmaster*',
			'VEX Robotics*',
		],
		backups: ['On Demand Video', 'Video Game Design*'],
	},
	{
		id: '30',
		name: 'HARRY ALLEN',
		email: 's-hallen@lwsd.org',
		startTime: '9/30/23 21:45:04',
		lastModifiedTime: '',
		completionTime: '9/30/23 21:46:43',
		events: [
			'Coding',
			'Software Development*',
			'Technology Bowl',
			'Technology Problem Solving',
			'Webmaster*',
			'VEX Robotics*',
		],
		backups: ['On Demand Video', 'Video Game Design*'],
	},
	{
		id: '31',
		name: 'RITVIJ GARG',
		email: 's-rgarg@lwsd.org',
		startTime: '9/30/23 21:58:30',
		lastModifiedTime: '10/20/23 8:31:39',
		completionTime: '9/30/23 21:59:31',
		events: [
			'Debating Technological Issues*',
			'Essays on Technology',
			'Extemporaneous Speech',
			'Career Prep* (Washington Only)',
			'Prepared Presentation*',
			'Biotechnology Design*',
		],
		backups: ['Data Science and Analytics*', 'Biotechnology Design*'],
	},
	{
		id: '32',
		name: 'WENJUAN ZOU',
		email: 's-wzou@lwsd.org',
		startTime: '9/30/23 22:09:40',
		lastModifiedTime: '',
		completionTime: '9/30/23 22:13:19',
		events: [
			'On Demand Video',
			'VEX Robotics*',
			'Technology Problem Solving',
			'Webmaster*',
			'Virtual Reality Visualization (VR)*',
			'Software Development*',
		],
		backups: ['Audio Podcasting*', 'Forensic Science'],
	},
	{
		id: '33',
		name: 'TARAS ABAKUMOV',
		email: 's-tabakumov@lwsd.org',
		startTime: '10/1/23 14:49:43',
		lastModifiedTime: '',
		completionTime: '10/1/23 14:51:18',
		events: [
			'Board Game Design*',
			'Technology Bowl',
			'Video Game Design*',
			'On Demand Video',
		],
		backups: ['VEX Robotics*', 'Technology Problem Solving'],
	},
	{
		id: '34',
		name: 'JANA BERAHMAN',
		email: 's-jberahman@lwsd.org',
		startTime: '10/1/23 17:37:36',
		lastModifiedTime: '10/24/23 15:34:14',
		completionTime: '10/1/23 17:42:17',
		events: [
			'Audio Podcasting*',
			"Children's Stories*",
			'Extemporaneous Speech',
			'Prepared Presentation*',
			'Animation (Washington Only)',
			'Architectural Design*',
		],
		backups: ['Photographic Technology', 'Career Prep* (Washington Only)'],
	},
	{
		id: '35',
		name: 'ALEXANDER TARNAVSKI',
		email: 's-atarnavski@lwsd.org',
		startTime: '10/2/23 9:55:07',
		lastModifiedTime: '',
		completionTime: '10/2/23 9:57:09',
		events: [
			'Coding',
			'Senior Solar Sprint*',
			'Software Development*',
			'Drone Challenge (UAV)*',
			'Trebuchet (Washington Only)',
			'Video Game Design*',
		],
		backups: ['Music Production*', 'Prepared Presentation*'],
	},
	{
		id: '36',
		name: 'SRISAIMEENAKSHI ARASADA',
		email: 's-sarasada@lwsd.org',
		startTime: '10/2/23 13:49:17',
		lastModifiedTime: '10/14/23 20:28:57',
		completionTime: '10/2/23 13:54:11',
		events: [
			'Webmaster*',
			'Coding',
			'On Demand Video',
			'Software Development*',
			'Biotechnology Design*',
			'Architectural Design*',
		],
		backups: ['Forensic Science', 'Future Technology Teacher*'],
	},
	{
		id: '37',
		name: 'MUSTAFA QAZI',
		email: 's-mqazi@lwsd.org',
		startTime: '10/2/23 15:27:30',
		lastModifiedTime: '10/12/23 16:09:07',
		completionTime: '10/2/23 15:29:42',
		events: [
			'Coding',
			'Software Development*',
			'Technology Bowl',
			'Silent Film (Washington Only)',
			'Debating Technological Issues*',
		],
		backups: ['Extemporaneous Speech', 'Technology Problem Solving'],
	},
	{
		id: '38',
		name: 'MARLIN WONG',
		email: 's-mwong@lwsd.org',
		startTime: '10/2/23 15:29:57',
		lastModifiedTime: '10/8/23 17:43:22',
		completionTime: '10/2/23 15:31:31',
		events: [
			'Coding',
			'Data Science and Analytics*',
			'Drone Challenge (UAV)*',
			'Technology Bowl',
			'Trebuchet (Washington Only)',
			'Webmaster*',
		],
		backups: ['Video Game Design*', 'Geospatial Technology*'],
	},
	{
		id: '39',
		name: 'ASHLEY LI',
		email: 's-ASLI@lwsd.org',
		startTime: '10/2/23 15:33:37',
		lastModifiedTime: '10/5/23 16:14:11',
		completionTime: '10/2/23 15:35:12',
		events: [
			'Architectural Design*',
			'Software Development*',
			'Biotechnology Design*',
			'Fashion Design and Technology*',
			'Trebuchet (Washington Only)',
		],
		backups: ['Coding', 'Essays on Technology'],
	},
	{
		id: '40',
		name: 'AMEYA BHIDE',
		email: 's-abhide@lwsd.org',
		startTime: '10/2/23 15:47:51',
		lastModifiedTime: '',
		completionTime: '10/2/23 15:51:46',
		events: [
			'Coding',
			'Debating Technological Issues*',
			'Senior Solar Sprint*',
			'Software Development*',
			'Virtual Reality Visualization (VR)*',
			'Drone Challenge (UAV)*',
		],
		backups: ['Essays on Technology', 'Prepared Presentation*'],
	},
	{
		id: '41',
		name: 'VEER DESAI',
		email: 's-VDESAI@lwsd.org',
		startTime: '10/2/23 16:27:39',
		lastModifiedTime: '10/12/23 15:43:09',
		completionTime: '10/2/23 16:30:43',
		events: [
			'Virtual Reality Visualization (VR)*',
			'Essays on Technology',
			'Drone Challenge (UAV)*',
			'Silent Film (Washington Only)',
			'Video Game Design*',
			'Engineering Design*',
		],
		backups: ['Video Game Design*', 'Webmaster*'],
	},
	{
		id: '42',
		name: 'KATREEYA ONG',
		email: 's-kong@lwsd.org',
		startTime: '10/2/23 16:30:59',
		lastModifiedTime: '10/3/23 21:10:53',
		completionTime: '10/2/23 16:31:24',
		events: [
			'Architectural Design*',
			'Biotechnology Design*',
			'Fashion Design and Technology*',
			'Trebuchet (Washington Only)',
			'Infographic (Washington Only)',
		],
		backups: ["Children's Stories*", 'Promotional Design'],
	},
	{
		id: '43',
		name: 'ALEX LAVIER',
		email: 's-alavier@lwsd.org',
		startTime: '10/2/23 17:43:36',
		lastModifiedTime: '10/26/23 16:05:48',
		completionTime: '10/2/23 17:44:21',
		events: [
			'Photographic Technology',
			'Engineering Design*',
			'Video Game Design*',
			'Architectural Design*',
			'On Demand Video',
			'Silent Film (Washington Only)',
		],
		backups: ['VEX Robotics*', 'Drone Challenge (UAV)*'],
	},
	{
		id: '44',
		name: 'ANIRUDH KUMAR',
		email: 's-anikumar@lwsd.org',
		startTime: '10/3/23 8:25:01',
		lastModifiedTime: '10/12/23 8:16:40',
		completionTime: '10/3/23 8:25:14',
		events: [
			'Forensic Science',
			'Music Production*',
			'Biotechnology Design*',
			'Debating Technological Issues*',
			'Silent Film (Washington Only)',
		],
		backups: [
			'Essays on Technology',
			'Computer-Aided Design (CAD), Architecture',
		],
	},
	{
		id: '45',
		name: 'SIMON RUNDLE',
		email: 's-srundle@lwsd.org',
		startTime: '10/3/23 10:24:30',
		lastModifiedTime: '',
		completionTime: '10/3/23 10:25:54',
		events: [
			'Architectural Design*',
			'Board Game Design*',
			"Children's Stories*",
			'Digital Video Production*',
			'Engineering Design*',
			'On Demand Video',
		],
		backups: ['Engineering Design*', 'Extemporaneous Speech'],
	},
	{
		id: '46',
		name: 'NORA REDMOND',
		email: 's-nredmond@lwsd.org',
		startTime: '10/3/23 16:27:53',
		lastModifiedTime: '10/8/23 21:52:17',
		completionTime: '10/3/23 16:47:47',
		events: [
			'Architectural Design*',
			'Forensic Science',
			'Debating Technological Issues*',
			'Music Production*',
			'Technology Problem Solving',
		],
		backups: ['Biotechnology Design*', 'Technology Problem Solving'],
	},
	{
		id: '47',
		name: 'EVAN DUONG',
		email: 's-evduong@lwsd.org',
		startTime: '10/3/23 18:01:55',
		lastModifiedTime: '',
		completionTime: '10/3/23 18:02:41',
		events: [
			'Board Game Design*',
			'On Demand Video',
			'Technology Bowl',
			'Video Game Design*',
		],
		backups: ['VEX Robotics*', 'Computer-Aided Design (CAD), Engineering'],
	},
	{
		id: '48',
		name: 'SHAQED COHENATIR',
		email: 's-scohenatir@lwsd.org',
		startTime: '10/3/23 19:13:33',
		lastModifiedTime: '',
		completionTime: '10/3/23 19:15:29',
		events: [
			'Audio Podcasting*',
			'Architectural Design*',
			'Fashion Design and Technology*',
			'Music Production*',
		],
		backups: ['Video Game Design*', 'Career Prep* (Washington Only)'],
	},
	{
		id: '49',
		name: 'ANEESH MANAGULI',
		email: 's-amanaguli@lwsd.org',
		startTime: '10/3/23 19:54:48',
		lastModifiedTime: '',
		completionTime: '10/3/23 20:35:54',
		events: [
			'Career Prep* (Washington Only)',
			'Technology Problem Solving',
			'Forensic Science',
			'Prepared Presentation*',
		],
		backups: ['Essays on Technology', 'Extemporaneous Speech'],
	},
	{
		id: '50',
		name: 'ANIKA YANG',
		email: 's-anyang@lwsd.org',
		startTime: '10/3/23 21:04:31',
		lastModifiedTime: '',
		completionTime: '10/3/23 21:46:12',
		events: [
			'Animatronics*',
			'Fashion Design and Technology*',
			'Animation (Washington Only)',
			'Concept Art (Washington Only)',
		],
		backups: ["Children's Stories*", 'On Demand Video'],
	},
	{
		id: '51',
		name: 'ADVAITH RAMASWAMY',
		email: 's-aramaswamy@lwsd.org',
		startTime: '10/3/23 21:48:08',
		lastModifiedTime: '10/12/23 15:27:34',
		completionTime: '10/3/23 21:51:00',
		events: [
			'Senior Solar Sprint*',
			'Drone Challenge (UAV)*',
			'Essays on Technology',
			'Silent Film (Washington Only)',
		],
		backups: ['Forensic Science', 'Photographic Technology'],
	},
	{
		id: '52',
		name: 'HENRY MASON',
		email: 's-hmason@lwsd.org',
		startTime: '10/4/23 9:52:57',
		lastModifiedTime: '10/25/23 10:40:04',
		completionTime: '10/4/23 9:54:21',
		events: [
			'Architectural Design*',
			'Photographic Technology',
			'Prepared Presentation*',
			'Drone Challenge (UAV)*',
		],
		backups: ['Career Prep* (Washington Only)', 'Trebuchet (Washington Only)'],
	},
	{
		id: '53',
		name: 'GALAL ELTAWEEL',
		email: 's-geltaweel@lwsd.org',
		startTime: '10/4/23 9:47:01',
		lastModifiedTime: '',
		completionTime: '10/4/23 10:11:36',
		events: [
			'Career Prep* (Washington Only)',
			'Prepared Presentation*',
			'Trebuchet (Washington Only)',
			'Engineering Design*',
			'Photographic Technology',
		],
		backups: ['Technology Problem Solving', 'Data Science and Analytics*'],
	},
	{
		id: '54',
		name: 'SOFIA DELOOZE',
		email: 's-sdelooze@lwsd.org',
		startTime: '10/4/23 9:53:28',
		lastModifiedTime: '10/12/23 15:45:29',
		completionTime: '10/4/23 11:01:36',
		events: [
			'Architectural Design*',
			'Audio Podcasting*',
			"Children's Stories*",
			'Prepared Presentation*',
			'Technology Problem Solving',
			'Photographic Technology',
		],
		backups: [
			'Career Prep* (Washington Only)',
			'Silent Film (Washington Only)',
		],
	},
	{
		id: '55',
		name: 'GABRIELLA HESS',
		email: 's-ghess@lwsd.org',
		startTime: '10/4/23 19:30:57',
		lastModifiedTime: '',
		completionTime: '10/4/23 19:33:58',
		events: [
			'Forensic Science',
			'Board Game Design*',
			"Children's Stories*",
			'Dragster Design*',
		],
		backups: ['Architectural Design*', 'Biotechnology Design*'],
	},
	{
		id: '56',
		name: 'LIV HILMAR',
		email: 's-lhilmar@lwsd.org',
		startTime: '10/4/23 19:34:57',
		lastModifiedTime: '',
		completionTime: '10/4/23 20:02:08',
		events: [
			'Forensic Science',
			'Board Game Design*',
			"Children's Stories*",
			'Dragster Design*',
		],
		backups: ['Music Production*', 'Architectural Design*'],
	},
	{
		id: '59',
		name: 'SAIANIVARTH SANKARA',
		email: 's-ssankara@lwsd.org',
		startTime: '10/4/23 22:00:07',
		lastModifiedTime: '10/12/23 16:16:56',
		completionTime: '10/4/23 22:25:12',
		events: [
			'Biotechnology Design*',
			'Board Game Design*',
			'Forensic Science',
			'Debating Technological Issues*',
		],
		backups: ['Audio Podcasting*', 'Trebuchet (Washington Only)'],
	},
	{
		id: '60',
		name: 'ISAIAH LEONG',
		email: 's-ileong@lwsd.org',
		startTime: '10/5/23 9:38:32',
		lastModifiedTime: '10/26/23 16:17:42',
		completionTime: '10/5/23 9:41:40',
		events: [
			'VEX Robotics*',
			'Robotic Challenge* (Washington Only)',
			'Engineering Design*',
			'Dragster Design*',
			'Board Game Design*',
			"Children's Stories*",
		],
		backups: ['Architectural Design*', 'Board Game Design*'],
	},
	{
		id: '61',
		name: 'IDA SMITH',
		email: 's-idsmith@lwsd.org',
		startTime: '10/5/23 10:13:50',
		lastModifiedTime: '',
		completionTime: '10/5/23 10:15:46',
		events: [
			'Board Game Design*',
			"Children's Stories*",
			'Promotional Design',
			'Technology Problem Solving',
			'Transportation Modeling*',
			'Prepared Presentation*',
		],
		backups: [
			'Fashion Design and Technology*',
			'Concept Art (Washington Only)',
		],
	},
	{
		id: '62',
		name: 'PATRICK MCMANUS',
		email: 's-PMCMANUS@lwsd.org',
		startTime: '10/5/23 12:50:59',
		lastModifiedTime: '',
		completionTime: '10/5/23 12:52:47',
		events: [
			'Computer-Aided Design (CAD), Engineering',
			'Engineering Design*',
			'Technology Bowl',
			'Trebuchet (Washington Only)',
			'Flight Endurance*',
		],
		backups: ['Dragster Design*', 'Transportation Modeling*'],
	},
	{
		id: '65',
		name: 'SAISRISANJANA LINGAMALLU',
		email: 's-salingamallu@lwsd.org',
		startTime: '10/5/23 15:26:13',
		lastModifiedTime: '',
		completionTime: '10/5/23 15:39:13',
		events: [
			'Audio Podcasting*',
			"Children's Stories*",
			'Forensic Science',
			'Biotechnology Design*',
			'Fashion Design and Technology*',
			'Board Game Design*',
		],
		backups: ['Extemporaneous Speech', 'Prepared Presentation*'],
	},
	{
		id: '66',
		name: 'CAROLINA PROCTOR',
		email: 's-cproctor@lwsd.org',
		startTime: '10/5/23 15:34:54',
		lastModifiedTime: '',
		completionTime: '10/5/23 15:39:28',
		events: [
			'Audio Podcasting*',
			'Fashion Design and Technology*',
			'Flight Endurance*',
			'Music Production*',
			"Children's Stories*",
			'STEM Mass Media (Washington Only)',
		],
		backups: ['Board Game Design*', 'Silent Film (Washington Only)'],
	},
	{
		id: '67',
		name: 'CAITLIN COPLEY',
		email: 's-ccopley@lwsd.org',
		startTime: '10/5/23 15:38:21',
		lastModifiedTime: '',
		completionTime: '10/5/23 15:40:33',
		events: [
			'Biotechnology Design*',
			"Children's Stories*",
			'Board Game Design*',
			'Forensic Science',
			'Data Science and Analytics*',
		],
		backups: ['Audio Podcasting*', 'Concept Art (Washington Only)'],
	},
	{
		id: '68',
		name: 'MAHDI EL HUSSEINI',
		email: 's-MEL-HUSSEINI@lwsd.org',
		startTime: '10/5/23 15:37:08',
		lastModifiedTime: '',
		completionTime: '10/5/23 15:41:51',
		events: [
			'Drone Challenge (UAV)*',
			'Engineering Design*',
			'Coding',
			'Technology Bowl',
			'Video Game Design*',
			'Dragster Design*',
		],
		backups: ['Technology Problem Solving', 'Software Development*'],
	},
	{
		id: '69',
		name: 'ZAHID MANNAN',
		email: 's-zmannan@lwsd.org',
		startTime: '10/5/23 15:43:44',
		lastModifiedTime: '10/12/23 11:50:40',
		completionTime: '10/5/23 15:44:22',
		events: [
			"Children's Stories*",
			'Architectural Design*',
			'Photographic Technology',
			'Video Game Design*',
		],
		backups: ['Geospatial Technology*', 'Forensic Science'],
	},
	{
		id: '70',
		name: 'VIHAN AGARWAL',
		email: 's-vihagarwal@lwsd.org',
		startTime: '10/5/23 15:22:52',
		lastModifiedTime: '10/12/23 16:06:28',
		completionTime: '10/5/23 15:51:35',
		events: [
			'Video Game Design*',
			'Robotic Challenge* (Washington Only)',
			'Architectural Design*',
			'Photographic Technology',
		],
		backups: ['Webmaster*', 'Animatronics*'],
	},
	{
		id: '71',
		name: 'DEVINITY MCCRAY',
		email: 's-dmccray@lwsd.org',
		startTime: '10/5/23 16:11:19',
		lastModifiedTime: '',
		completionTime: '10/5/23 16:15:15',
		events: [
			'Audio Podcasting*',
			'Coding',
			'Digital Video Production*',
			'Music Production*',
			'Video Game Design*',
			'Concept Art (Washington Only)',
		],
		backups: ['Software Development*', 'Concept Art (Washington Only)'],
	},
	{
		id: '72',
		name: 'ELIZA HAMLET',
		email: 's-elhamlet@lwsd.org',
		startTime: '10/5/23 16:19:44',
		lastModifiedTime: '',
		completionTime: '10/5/23 16:21:03',
		events: [
			'Board Game Design*',
			"Children's Stories*",
			'Essays on Technology',
			'Fashion Design and Technology*',
		],
		backups: ['Audio Podcasting*', 'Essays on Technology'],
	},
	{
		id: '73',
		name: 'LUCY ROTH',
		email: 's-lroth@lwsd.org',
		startTime: '10/5/23 16:30:20',
		lastModifiedTime: '',
		completionTime: '10/5/23 16:33:25',
		events: [
			"Children's Stories*",
			'Fashion Design and Technology*',
			'Music Production*',
			'Animation (Washington Only)',
		],
		backups: ['Silent Film (Washington Only)', 'Board Game Design*'],
	},
	{
		id: '74',
		name: 'KARUNYA PENUMALLA',
		email: 's-kpenumalla@lwsd.org',
		startTime: '10/5/23 19:41:46',
		lastModifiedTime: '10/26/23 20:04:51',
		completionTime: '10/5/23 19:43:49',
		events: [
			'Drone Challenge (UAV)*',
			'Video Game Design*',
			'Robotic Challenge* (Washington Only)',
			'VEX Robotics*',
			'Manufacturing Prototype*',
			'Coding',
		],
		backups: ['Software Development*', 'Digital Video Production*'],
	},
	{
		id: '75',
		name: 'OLIVIA KASPRICK',
		email: 's-okasprick@lwsd.org',
		startTime: '10/6/23 9:09:26',
		lastModifiedTime: '',
		completionTime: '10/6/23 9:10:31',
		events: [
			'Architectural Design*',
			'Board Game Design*',
			'Fashion Design and Technology*',
			'Forensic Science',
		],
		backups: ['Photographic Technology', 'Technology Problem Solving'],
	},
	{
		id: '76',
		name: 'JONATHAN KONG',
		email: 's-jkong@lwsd.org',
		startTime: '10/6/23 15:14:33',
		lastModifiedTime: '',
		completionTime: '10/8/23 22:32:35',
		events: ['Technology Bowl', 'On Demand Video'],
		backups: ['Flight Endurance*', 'Board Game Design*'],
	},
	{
		id: '78',
		name: 'ARNAV GUPTA',
		email: 's-arnagupta@lwsd.org',
		startTime: '10/10/23 8:19:38',
		lastModifiedTime: '10/12/23 15:48:47',
		completionTime: '10/10/23 8:21:04',
		events: [
			'Architectural Design*',
			"Children's Stories*",
			'Photographic Technology',
			'Video Game Design*',
		],
		backups: ['Forensic Science', 'Geospatial Technology*'],
	},
	{
		id: '79',
		name: 'MEGHA RAMESH',
		email: 's-mramesh@lwsd.org',
		startTime: '10/11/23 12:04:47',
		lastModifiedTime: '10/12/23 15:22:19',
		completionTime: '10/11/23 12:06:38',
		events: [
			'Drone Challenge (UAV)*',
			'Computer-Aided Design (CAD), Engineering',
			'Dragster Design*',
			'Essays on Technology',
		],
		backups: ['Computer-Aided Design (CAD), Architecture', 'Flight Endurance*'],
	},
	{
		id: '81',
		name: 'BRADLEY BARKANS',
		email: 's-bbarkans@lwsd.org',
		startTime: '10/12/23 15:23:39',
		lastModifiedTime: '10/20/23 21:45:54',
		completionTime: '10/12/23 15:31:04',
		events: [
			'Video Game Design*',
			'Architectural Design*',
			'Drone Challenge (UAV)*',
			'Dragster Design*',
		],
		backups: ['Animatronics*', 'Technology Bowl'],
	},
	{
		id: '82',
		name: 'FINLAY BOULD',
		email: 's-fbould@lwsd.org',
		startTime: '10/12/23 15:48:47',
		lastModifiedTime: '',
		completionTime: '10/12/23 15:50:45',
		events: ['Flight Endurance*', 'Dragster Design*', 'Drone Challenge (UAV)*'],
		backups: ['Architectural Design*', 'Photographic Technology'],
	},
	{
		id: '83',
		name: 'BENJAMIN HAIL',
		email: 's-bhail@lwsd.org',
		startTime: '10/12/23 15:42:25',
		lastModifiedTime: '',
		completionTime: '10/12/23 16:05:44',
		events: [
			'Board Game Design*',
			'Structural Design and Engineering*',
			"Children's Stories*",
			'Photographic Technology',
		],
		backups: ['Coding', 'Dragster Design*'],
	},
	{
		id: '84',
		name: 'CAYDEN CHAN',
		email: 's-cachan@lwsd.org',
		startTime: '10/12/23 16:06:45',
		lastModifiedTime: '',
		completionTime: '10/12/23 16:09:05',
		events: [
			'Board Game Design*',
			"Children's Stories*",
			'Architectural Design*',
			'Biotechnology Design*',
			'Infographic (Washington Only)',
			'Forensic Science',
		],
		backups: ['Technology Bowl', 'Essays on Technology'],
	},
	{
		id: '85',
		name: 'ADRIAN PREIZLER',
		email: 's-apreizler@lwsd.org',
		startTime: '10/12/23 16:07:16',
		lastModifiedTime: '',
		completionTime: '10/12/23 16:10:52',
		events: [
			'Biotechnology Design*',
			'Board Game Design*',
			'Forensic Science',
			'Infographic (Washington Only)',
			'Architectural Design*',
		],
		backups: ['Technology Bowl', 'Essays on Technology'],
	},
	{
		id: '86',
		name: 'JACK SEGESSER',
		email: 's-jsegesser@lwsd.org',
		startTime: '10/12/23 16:13:01',
		lastModifiedTime: '',
		completionTime: '10/12/23 16:16:55',
		events: [
			'Board Game Design*',
			'Biotechnology Design*',
			'Debating Technological Issues*',
			'Forensic Science',
		],
		backups: ['Audio Podcasting*', 'Trebuchet (Washington Only)'],
	},
].map((s) => ({
	...s,
	email: s.email.toLowerCase(),
}));
