export const tShirtMap = new Map([
	['W XS' as const, 'W XS'],
	['W S' as const, 'W Small'],
	['W M' as const, 'W Medium'],
	['W L' as const, 'W Large'],
	['W XL' as const, 'W XL'],
	['W XXL' as const, 'W XXL'],
	['W XXXL' as const, 'W XXXL'],
	['M XS' as const, 'M XS'],
	['M S' as const, 'M Small'],
	['M M' as const, 'M Medium'],
	['M L' as const, 'M Large'],
	['M XL' as const, 'M XL'],
	['M XXL' as const, 'M XXL'],
	['M XXXL' as const, 'M XXXL'],
]);
