name = "tsa-grouping-thing"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date =  "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding =  "ASSETS"
directory = ".svelte-kit/cloudflare"
