name: Deploy to Firebase
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Functions dependencies
        run: cd functions && pnpm install && cd ..

      - name: Add Firebase service account
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > firebase-service-account.json

      - name: Install Firebase CLI
        run: pnpm install -g firebase-tools
      - name: Deploy to Firebase
        run: firebase deploy --project tsa-grouping-thing
      - name: Remove credentials file
        if: success() || failure()
        run: |
          rm firebase-service-account.json
